CREATE TABLE contato (
  id BIGINT(20) NOT NULL AUTO_INCREMENT,
  nome VARCHAR(150) NOT NULL,
  CONSTRAINT PK_CONTATO PRIMARY KEY(id),
  CONSTRAINT UC_NOME UNIQUE(nome)
);

CREATE TABLE telefone (
  id BIGINT(20) NOT NULL AUTO_INCREMENT,
  ddd VARCHAR(3) NOT NULL,
  numero VARCHAR(15) NOT NULL,
  tipo VARCHAR(20) NOT NULL,
  id_contato BIGINT(20) NOT NULL,
  CONSTRAINT PK_TELEFONE PRIMARY KEY(id),
  CONSTRAINT FK_ID_CONTATO_TELEFONE FOREIGN KEY (id_contato) REFERENCES contato (id)
);